name: Update Info

on:
  schedule:
    - cron: #Setup your cronjob here

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_AUTO }}

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: cd client/generate_info && npm install

    - name: Update repo
      run: git pull

    - name: Generate new info
      run: node client/generate_info/update_info.js

    - name: Commit and push if it changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git fetch
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -am "Update Classement $(date '+%Y-%m-%d %H:%M:%S')" && git push)
